#!/usr/bin/env python3
"""Build web-optimized gallery derivatives + manifest from trip originals.

Reads originals from SOURCE (default /home/tng/workspace/2026_jp_trip/media),
writes thumbnails and full-size derivatives into site/assets/gallery/, and
generates site/_data/gallery.yml grouped by trip day (from filenames).

Requires: Pillow, ffmpeg, ffprobe. Originals are never modified or copied.

Usage:
  python3 site/scripts/build_gallery.py [--source PATH] [--force] [--regen-manifest]
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
from datetime import date

from PIL import Image, ImageOps

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)                      # .../site
THUMB_DIR = os.path.join(SITE, "assets", "gallery", "thumb")
FULL_DIR = os.path.join(SITE, "assets", "gallery", "full")
DATA_DIR = os.path.join(SITE, "_data")
MANIFEST = os.path.join(DATA_DIR, "gallery.yml")
DEFAULT_SOURCE = "/home/tng/workspace/2026_jp_trip/media"

NAME_RE = re.compile(r"^(2026-07-(\d{2})_\d{6}(?:_\d+)?)\.(jpg|jpeg|webp|mov)$", re.I)
PHOTO_EXT = {"jpg", "jpeg", "webp"}
VIDEO_EXT = {"mov"}
TRIP_START = date(2026, 7, 17)  # day_number = date - TRIP_START

THUMB_MAX = 400
FULL_MAX = 1600
VIDEO_MAX_H = 720


def require_tools():
    for tool in ("ffmpeg", "ffprobe"):
        if shutil.which(tool) is None:
            sys.exit(f"ERROR: '{tool}' not found. Install with: sudo apt-get install -y ffmpeg")


def newer(src, dst):
    """True if dst is missing or older than src."""
    return not os.path.exists(dst) or os.path.getmtime(dst) < os.path.getmtime(src)


def build_photo(src, base, force):
    thumb = os.path.join(THUMB_DIR, base + ".jpg")
    full = os.path.join(FULL_DIR, base + ".jpg")
    for dst, size, q in ((thumb, THUMB_MAX, 78), (full, FULL_MAX, 80)):
        if not force and not newer(src, dst):
            continue
        with Image.open(src) as im:
            im = ImageOps.exif_transpose(im).convert("RGB")
            im.thumbnail((size, size), Image.LANCZOS)
            im.save(dst, "JPEG", quality=q, optimize=True, progressive=True)


def build_video(src, base, force):
    full = os.path.join(FULL_DIR, base + ".mp4")
    thumb = os.path.join(THUMB_DIR, base + ".jpg")
    if force or newer(src, full):
        subprocess.run(
            ["ffmpeg", "-y", "-i", src, "-vf", f"scale=-2:'min({VIDEO_MAX_H},ih)'",
             "-c:v", "libx264", "-preset", "medium", "-crf", "23",
             "-c:a", "aac", "-b:a", "128k", "-movflags", "+faststart", full],
            check=True, stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
    if force or newer(src, thumb):
        subprocess.run(
            ["ffmpeg", "-y", "-i", src, "-vf",
             f"thumbnail,scale={THUMB_MAX}:{THUMB_MAX}:force_original_aspect_ratio=decrease",
             "-frames:v", "1", thumb],
            check=True, stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )


def yaml_escape(s):
    return '"' + s.replace('"', '\\"') + '"'


def write_manifest(days):
    """days: dict[date_str] -> list[(base, type)] already sorted."""
    lines = ["# Auto-generated by build_gallery.py. Hand edits are preserved",
             "# unless run with --regen-manifest. 'file' is basename without extension.",
             "days:"]
    for dstr in sorted(days):
        d = date.fromisoformat(dstr)
        lines.append(f"  - date: {yaml_escape(dstr)}")
        lines.append(f"    day_number: {(d - TRIP_START).days}")
        lines.append("    items:")
        for base, typ in days[dstr]:
            lines.append(f"      - {{ file: {yaml_escape(base)}, type: {typ} }}")
    os.makedirs(DATA_DIR, exist_ok=True)
    with open(MANIFEST, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", default=os.environ.get("GALLERY_SOURCE", DEFAULT_SOURCE))
    ap.add_argument("--force", action="store_true", help="rebuild derivatives even if up-to-date")
    ap.add_argument("--regen-manifest", action="store_true", help="overwrite existing gallery.yml")
    args = ap.parse_args()

    if not os.path.isdir(args.source):
        sys.exit(f"ERROR: source dir not found: {args.source}")
    require_tools()
    os.makedirs(THUMB_DIR, exist_ok=True)
    os.makedirs(FULL_DIR, exist_ok=True)

    days = {}
    files = sorted(os.listdir(args.source))
    total = 0
    for name in files:
        m = NAME_RE.match(name)
        if not m:
            continue
        base, dd, ext = m.group(1), m.group(2), m.group(3).lower()
        src = os.path.join(args.source, name)
        dstr = f"2026-07-{dd}"
        if ext in PHOTO_EXT:
            build_photo(src, base, args.force)
            days.setdefault(dstr, []).append((base, "photo"))
        elif ext in VIDEO_EXT:
            build_video(src, base, args.force)
            days.setdefault(dstr, []).append((base, "video"))
        total += 1
        print(f"[{total}] {name}")

    for dstr in days:
        days[dstr].sort(key=lambda t: t[0])

    if args.regen_manifest or not os.path.exists(MANIFEST):
        write_manifest(days)
        print(f"Wrote manifest: {MANIFEST}")
    else:
        print(f"Manifest exists, kept as-is (use --regen-manifest to overwrite): {MANIFEST}")

    print(f"Done. Processed {total} files across {len(days)} days.")


if __name__ == "__main__":
    main()
